language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install: 
  - npm update -g npm
  - "sudo apt-get install ruby-compass"
  - "npm install -g grunt grunt-cli bower"
before_script:
  - mysql -e 'create database shwopDB;'
script:
  - "grunt test"
  - "grunt runSass"
  # - "grunt ugly"
