language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install: 
  - npm update -g npm
  - "sudo apt-get install ruby-compass"
  - "npm install -g grunt grunt-cli bower"
script:
  - "npm test"
  - "grunt runSass"
  - "grunt ugly"
