language: node_js
node_js:
  - '0.12.7'
  - '0.10'
before_install: 
  - npm update -g npm
  - "sudo apt-get install ruby-compass"
  - "npm install -g grunt grunt-cli bower"
before_script:
  - mysql -e 'create database shwopDB;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - "grunt test"
  - "grunt runSass"
  # - "grunt ugly"
